name: complete-cicd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    # build-and-test:
    #     uses: ./.github/workflows/Build.yml

    # test:
    #     needs: build-and-test
    #     uses: ./.github/workflows/test.yml
    
    docker-build-push:
        #needs: test
        uses: ./.github/workflows/docker-build-push.yml
