name: docker-build-push

on:
    workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check docker secrets
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKER_USERNAME secret is not set."
            exit 1
          fi
          if [ -z "$DOCKER_TOKEN" ]; then
            echo "DOCKER_TOKEN secret is not set."
            exit 1
          fi
      

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_TOKEN
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:latest