name: test-applicatiom\

on:
  workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Java21
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '21'

            - name: MVN Test
              run: mvn test